# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a8e7f9c5d438e2744148f80ebff2498866e0e0c5a6cd41695d53efe85e9c83f8b5e6666dcac3c4b174cb66ace96343482837780f114ccba64e351d272cea0a

test:
  secret_key_base: 1ac3ad7f31d313b5f634142216f9c5bcc975a948e44d37ebe1abe821d242dc78ed1c00a9fe6ca7d611bcc2a009db89e5e0b3a12b9c69aac99415746ca7cd2af5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
